spring:
  jwt:
    expiration:
      access-token: 21600000
      refresh-token: 86400000
  datasource:
    url: jdbc:mysql://localhost:3306/flolink?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    redis:
      url: localhost
      port: 6380
      connect-timeout: 3000
      timeout: 3000
      repositories:
        enabled: false
  config:
    import:
      - classpath:/application-private.yml
  profiles:
    active: blue
    group:
      blue:
        - private
      green:
        - private
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  prometheus:
    metrics:
      export:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: green
server:
  port: 8082
---



