spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flolink?useSSL=false&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    import:
      - classpath:/application-private.yml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Demo API
    description: Demo API for Spring Boot application
    version: 1.0.0

logging.level:
  org.hibernate.SQL: debug
